export const CONTACT_FETCH_REQUEST = "CONTACT_FETCH_REQUEST";
export const CONTACT_FETCH_SUCCESS = "CONTACT_FETCH_SUCCESS";
export const CONTACT_FETCH_FAIL = "CONTACT_FETCH_FAIL";

export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
